version: '3.9'
services:
  db:
    restart: always
    image:  postgres
    container_name: db_auth
   
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: shio
      POSTGRES_DB: teatr
    ports:
      - "5433:5432"
    volumes:
      -
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
