FROM  python:3.11
RUN mkdir /app
COPY  . /app/
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install aiogram
RUN pip install bs4
RUN pip install mysql-connector-python
RUN pip install requests


ENTRYPOINT [ "python","main.py"]

CMD ["run main.py"]